name: pkl-lang-cli-action

author: Draftea

description: Setup pkl-lang CLI to interact with it

branding:
  icon: box
  color: blue

inputs:
  version:
    description: Desired pkl version.
    default: "0.25.3"
  args:
    description: pkl command arguments to execute.
    default: "--version"

runs:
  using: composite
  steps:
    - name: Setup PKL CLI
      shell: bash
      run: |
        curl -L -o pkl https://github.com/apple/pkl/releases/download/${{ inputs.version }}/pkl-alpine-linux-amd64
        chmod +x pkl
        ./pkl --version

    - name: Execute command
      shell: bash
      run: |
        ./pkl ${{ inputs.args }}